name: Blue-Green Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name <your-cluster-name>

      - name: Deploy Green
        run: |
          kubectl apply -f k8s/deployment-green.yaml
          kubectl apply -f k8s/service.yaml

      # Optionally, switch traffic to green by updating the service selector
      # - name: Switch Service to Green
      #   run: |
      #     kubectl patch service demo-service -n default -p '{"spec":{"selector":{"app":"demo","version":"green"}}}'

      # To rollback, you can patch the service back to blue