name: Blue-Green Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'blue'
        type: choice
        options:
          - blue
          - green

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name Blue-Green

      - name: Deploy Green
        if: ${{ github.event.inputs.environment == 'green' }}
        run: |
          kubectl apply -f k8s/deployment-green.yaml
          kubectl apply -f k8s/green-service.yaml

      - name: Deploy Blue
        if: ${{ github.event.inputs.environment == 'blue' }}
        run: |
          kubectl apply -f k8s/deployment-blue.yaml
          kubectl apply -f k8s/service.yaml

      # Optional: Switch traffic to green
      # - name: Switch Service to Green
      #   if: ${{ github.event.inputs.environment == 'green' }}
      #   run: |
      #     kubectl patch service demo-service -n default -p '{"spec":{"selector":{"app":"demo","version":"green"}}}'

      # Optional: Rollback logic could go here
